export { default as SignIn } from "./SignIn";
export { default as About } from "./About";
export { default as Home } from "./Home";
export { default as Documents } from "./Documents";
export { default as Postulation } from "./Postulation";
export { default as Results } from "./Results";
export { default as Dashboard } from "./Dashboard";
export { default as Vote } from "./vote";
export { default as Postulate } from "./Postulate";
